
version: "3.6"
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ${PWD}/src:/opt/app:cached
    ports:
      - "8000:8000"
  db:  
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: "password"
