name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run app
        run: docker-compose up -d web app
      
      - name: Wait until app starts
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
    
      - name: Check app is running
        run: bash -c 'if [ $(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080) == 200 ]; then exit 0; else exit 1; fi'
      
      - name: Teardown
        run: docker-compose down
